INSERT INTO BOOKS VALUES('ABC','ABC',2000);
INSERT INTO BOOKS VALUES('ABC','ABC',2000);
INSERT INTO BOOKS VALUES('ABC','ABC',2000);
INSERT INTO BOOKS VALUES('ABC','ABC',2000);
INSERT INTO BOOKS VALUES('ABC','ABC',2000);